### ISSUE TITLE
Added toggle extras

### ISSUE THREAD

**Issue by WillIShocker** [djjackYT/qb-radialmenu-npstyle#2]
The code is already in client side, all anyone needs to do is add this at line 1122 in the config to toggle extras -
},  {
            id = 'vehicleextras',
            title = 'Vehicle Extras',
            icon = 'plus',
            type = 'client',
            items = {
                    {
                    id = 'extra1',
                    title = 'Extra 1',
                    icon = 'box-open',
                    type = 'client',
                    event = 'qb-radialmenu:client:setExtra',
                    shouldClose = false
                    }, {
                    id = 'extra2',
                    title = 'Extra 2',
                    icon = 'box-open',
                    type = 'client',
                    event = 'qb-radialmenu:client:setExtra',
                    shouldClose = false
                    }, {
                    id = 'extra3',
                    title = 'Extra 3',
                    icon = 'box-open',
                    type = 'client',
                    event = 'qb-radialmenu:client:setExtra',
                    shouldClose = false
                    }, {
                    id = 'extra4',
                    title = 'Extra 4',
                    icon = 'box-open',
                    type = 'client',
                    event = 'qb-radialmenu:client:setExtra',
                    shouldClose = false
                    }, {
                    id = 'extra5',
                    title = 'Extra 5',
                    icon = 'box-open',
                    type = 'client',
                    event = 'qb-radialmenu:client:setExtra',
                    shouldClose = false
                    }, {
                    id = 'extra6',
                    title = 'Extra 6',
                    icon = 'box-open',
                    type = 'client',
                    event = 'qb-radialmenu:client:setExtra',
                    shouldClose = false
                    }, {
                    id = 'extra7',
                    title = 'Extra 7',
                    icon = 'box-open',
                    type = 'client',
                    event = 'qb-radialmenu:client:setExtra',
                    shouldClose = false
                    }, {
                    id = 'extra8',
                    title = 'Extra 8',
                    icon = 'box-open',
                    type = 'client',
                    event = 'qb-radialmenu:client:setExtra',
                    shouldClose = false
                    }, {
                    id = 'extra9',
                    title = 'Extra 9',
                    icon = 'box-open',
                    type = 'client',
                    event = 'qb-radialmenu:client:setExtra',
                    shouldClose = false
                    }, {
                    id = 'extra10',
                    title = 'Extra 10',
                    icon = 'box-open',
                    type = 'client',
                    event = 'qb-radialmenu:client:setExtra',
                    shouldClose = false
                    }, {
                    id = 'extra11',
                    title = 'Extra 11',
                    icon = 'box-open',
                    type = 'client',
                    event = 'qb-radialmenu:client:setExtra',
                    shouldClose = false
                    }, {
                    id = 'extra12',
                    title = 'Extra 12',
                    icon = 'box-open',
                    type = 'client',
                    event = 'qb-radialmenu:client:setExtra',
                    shouldClose = false
                    }, {
                    id = 'extra13',
                    title = 'Extra 13',
                    icon = 'box-open',
                    type = 'client',
                    event = 'qb-radialmenu:client:setExtra',
                    shouldClose = false
                }        
            }
        }
    },

**Comment by thaatguyjaack** [comment]
To make it more like Nopixel, we don't have any of the vehicle stuff from the normal qbcore radialmenu. If you want to make a fork with that then go right ahead
