### ISSUE TITLE
Radial Menu locks up screen

### ISSUE THREAD

**Issue by FloridaFiend** [djjackYT/qb-radialmenu-npstyle#4]
When using the Radial menu after installing it, I will try to use one of the menu options. The Menu disappears and locks the cursor on the stream and prevents players from moving, opening chat, or using other menus. FiveM will register other menu's opening up from clicking keyboard binds but will not allow anyone to control it.

Not sure what needs to be done on my end to fix it

**Comment by OhhhBeans** [comment]
Same issue here. To every point.

**Comment by thaatguyjaack** [comment]
What's the F8 message look like?
