### ISSUE TITLE
QoL changes

### ISSUE THREAD

**Issue by LividDS** [djjackYT/qb-radialmenu-npstyle#5]
I personally really like the style of this radialmenu, clean looking and smooth. The only thing I have an issue with is the fact the menu doesn't close when you release F1, this causes issues because at that point it considers it a menu, which semi tabs you out. 

I'm fairly new to scripts and the understanding of the code. So I wonder if you'd be able to make it so that you have to hold F1 in order to keep it open, alike many other radialmenus, including qb's standard radialmenu?

**Comment by thaatguyjaack** [comment]
Its coming soon! Sorry for not responding, doing a lot of work on servers atm.

**Comment by GetBackJames** [comment]
Holding F1 is a terrible idea and is horrible for servers that have a big player base due to 60% keyboards, i would recommend having that as a config option or a lot of people will stop using the resource as the most highly requested radial menu option is push not hold.

**Comment by thaatguyjaack** [comment]
> Holding F1 is a terrible idea and is horrible for servers that have a big player base due to 60% keyboards, i would recommend having that as a config option or a lot of people will stop using the resource as the most highly requested radial menu option is push not hold.

I can include an optional instruction that tells you how to get rid of it. Don't know if I can make it a config due to one being java and the config being in lua.

**Comment by GetBackJames** [comment]
> > Holding F1 is a terrible idea and is horrible for servers that have a big player base due to 60% keyboards, i would recommend having that as a config option or a lot of people will stop using the resource as the most highly requested radial menu option is push not hold.
> 
> I can include an optional instruction that tells you how to get rid of it. Don't know if I can make it a config due to one being java and the config being in lua.

Your right and I didn't think about that at the time, and I agree with adding a snippet or portion of the ReadMe on how to disable the press option.

**Comment by thaatguyjaack** [comment]
Alright Cool! Do it soon
