### ISSUE TITLE
Vehicle Extras

### ISSUE THREAD

**Issue by flash061** [djjackYT/qb-radialmenu-npstyle#7]
Is there any way that vehicle extras can be added to this?  I've tried and cannot seem to get it to work?

**Comment by thaatguyjaack** [comment]
Yes there is. Keep in mind this is still the QBCore radialmenu just heavily modified to look like nopixel. Just look at the stock qb-radialmenu and you should be able to find vehicle extra's and just copy and paste. Should be pretty easy to do

**Comment by flash061** [comment]
Yeah I tried that mate, didn't seem to work for me, I'll definitely give it
another rattle, because I can finally get rid of qb-customs then lol

**Comment by flash061** [comment]
Hi mate, I fixed it and got it working :)

**Comment by thaatguyjaack** [comment]
Wonderful! Glad to hear that.
